### ISSUE TITLE
New Crypto Icon

### ISSUE THREAD

**Issue by s1-ranjan** [bluppfisk/coinprice-indicator#56]
I have found a very good collection of Icon set on Github located at --> [AllienWorks](https://github.com/AllienWorks/cryptocoins)
I consider by using this icon set will add support for many new Icons in this application.

**Comment by bluppfisk** [comment]
Thanks for these. I won't use them because
* I personally prefer the coloured icons, and
* LibAppIndicator does not support SVG images.

However, if you put in the time to turn them into PNG images, you can simply save them into the **resources** folder of your installation, as **asset.png** (where asset is the abbreviation of the asset in lowercase, e.g. btc.png, eos.png). When you restart the indicator, it should automatically load the correct image.

You're also welcome to do a pull request if you want to add any to the repository.
